<?php
/**
 * @file
 * Hello World module to demonstrate grasp of Drupal API to Mediacurrent
 */

define('HELLO_WORLD_DEFAULT_THEME', 'bartik');
define('HELLO_WORLD_VOCABULARY', 'sections');
define('HELLO_WORLD_NODE_BUNDLE', 'hello_world_article');

/**
 * Implements hook_theme().
 */
function hello_world_theme() {
  $return = array(
    'hello_world_articles_block' => array(
      'variables' => array('nodes' => NULL),
    ),
    'node__hello_world_article' => array(
      'render element' => 'content',
      'base hook' => 'node',
      'template' => 'node--hello-world-article',
      'path' => drupal_get_path('module', 'hello_world') . '/templates',
    ),
  );
  return $return;
}

/**
 * Implements hook_block_info().
 */
function hello_world_block_info() {
  $blocks = array();

  $blocks['hello_world'] = array(
    'info' => t('Hello world block'),
    'region' => 'sidebar_second',
  );

  return $blocks;
}

/**
 * Implements hook_block_info_alter().
 */
function hello_world_block_info_alter(&$blocks, $theme, $code_blocks) {
  if ($theme == variable_get('theme_default', '0')) {
    if (!path_is_admin(current_path())) {
      if (isset($blocks['hello_world']['hello_world'])) {
        $blocks['hello_world']['hello_world']['status'] = 1;
        $blocks['hello_world']['hello_world']['region'] = 'sidebar_second';
        $blocks['hello_world']['hello_world']['weight'] = 1;
      }
    }
  }
}

/**
 * Implements hook_block_view().
 */
function hello_world_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'hello_world':
      $block['subject'] = t('Hello World!');
      $block['content'] = theme('hello_world_articles_block', array(
          'nodes' => hello_world_get_links_to_hello_world_articles(),
        ));
      break;
  }

  return $block;
}

/**
 * Implements hook_block_list_alter().
 */
function hello_world_block_list_alter(&$blocks) {
  $node = menu_get_object();

  foreach ($blocks as $key => $block) {
    // Only display the hello_world block on hello_world_articles.
    if (!empty($node) && $node->type != 'hello_world_article' && $block->delta == 'hello_world') {
      unset($blocks[$key]);
      continue;
    }
  }
}

/**
 * Returns HTML for a list of of hello world articles.
 *
 * @param array $variables
 *   An associative array containing:
 *   - nodes: Loaded entity objects.
 *
 * @ingroup themeable
 *
 * @return string
 *   The output to be rendered.
 */
function theme_hello_world_articles_block($variables) {
  $output = '';
  foreach ($variables['nodes'] as $node) {
    $links[] = array(
      'title' => $node->title,
      'href' => 'node/' . $node->nid,
    );
  }

  $output .= theme('links', array(
      'links' => $links,
      'attributes' => array('class' => array('links'))));
  return $output;
}

/**
 * Gets links to the hello world articles.
 *
 * @return array
 *   Array of links to hello world articles.
 */
function hello_world_get_links_to_hello_world_articles() {

  $terms = hello_world_get_enabled_section_tids();

  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'hello_world_article')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldCondition('field_sections', 'tid', $terms, 'IN')
    ->range(0, 4);

  $result = $query->execute();

  if (!empty($result) && isset($result['node'])) {
    $article_item_nids = array_keys($result['node']);
    $article_items = entity_load('node', $article_item_nids);
    return $article_items;
  }

  return FALSE;
}

/**
 * Gets tids of all enabled terms from the sections vocab.
 *
 * @return array
 *   Array of tids.
 */
function hello_world_get_enabled_section_tids() {
  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'taxonomy_term')
    ->entityCondition('bundle', HELLO_WORLD_VOCABULARY)
    ->fieldCondition('field_enabled', 'value', 1);


  $result = $query->execute();

  if (!empty($result) && isset($result['taxonomy_term'])) {
    $tids = array_keys($result['taxonomy_term']);
    return $tids;
  }
}
